const medicalDataStyles = {
  pageBox: { p: 4 },
  sectionCard: (mb = 0) => ({
    background: '#f0fdfa',
    border: '0.5px solid #99f6e4',
    borderRadius: '12px',
    padding: 3,
    mb,
  }),
  title: { mb: 2, color: '#134e4a', fontWeight: 600 },
  smallHeading: { fontSize: '13px', fontWeight: 500, color: '#0f766e', mb: 1.5 },
  conditionPill: {
    fontSize: '12px',
    padding: '3px 10px',
    borderRadius: '99px',
    background: '#ccfbf1',
    border: '0.5px solid #99f6e4',
    color: '#0f766e',
  },
  conditionsWrap: { display: 'flex', flexWrap: 'wrap', gap: 0.75 },
  labCard: {
    background: '#ffffff',
    border: '0.5px solid #99f6e4',
    borderRadius: '12px',
    padding: '14px 16px',
    mb: 1.5,
    cursor: 'pointer',
    '&:hover': { background: '#f0fdfa' },
  },
  labCardHeaderTitle: { fontSize: '14px', color: '#134e4a', flexGrow: 1 },
  labCardDate: { fontSize: '11px', color: '#0f766e', whiteSpace: 'nowrap' },
  labCardHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between' },
  labCardHeaderRight: { display: 'flex', alignItems: 'center', gap: 1.5 },
  labCardExpanded: { mt: 1.5, pt: 1.5, borderTop: '0.5px solid #99f6e4' },
  resultsHeading: { fontSize: '13px', fontWeight: 500, color: '#134e4a', mb: 0.5 },
  resultsDetails: { fontSize: '13px', color: '#0f766e', mb: 1.5 },
  aiExplanationLabel: { fontSize: '12px', color: '#0d9488', fontStyle: 'italic', mb: 0.5 },
  aiDisclaimer: { fontSize: '11px', color: '#92400e', mb: 0.5 },
  explanationText: { fontSize: '13px', color: '#134e4a', lineHeight: 1.6 },
  generatingBox: { display: 'flex', alignItems: 'center', gap: 1 },
  generatingProgress: { color: '#0d9488' },
  generatingText: { fontSize: '13px', color: '#0f766e' },
  askButtonBox: { mt: 1 },
  askButton: { textTransform: 'none', borderColor: '#0d9488', color: '#0f766e' },
};

export default medicalDataStyles;
